# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

area_cpp <- function(x, y) {
    .Call(`_area_area_cpp`, x, y)
}

area_triangle_cpp <- function(x, y) {
    .Call(`_area_area_triangle_cpp`, x, y)
}

